Ssovras homework 10 done (with additional 2nd task)
eugene-okulik/SSovras pull request #10
Opened 2024-05-12 20:30 UTC by SergeiSovras

2024-05-15 10:12 UTC, eugene-okulik requested changes
Кроме последнего задания, всё круто.

2024-05-15 10:12 UTC, eugene-okulik commented on homework/sergei_sovras/Homework_10/Task_10_4.py
Хорошо, что воспользовался функцией zip. Но comprehension не воспользовался. А вот этот цикл for как раз можно превратить в list comprehension. В твоем случае, в два.

2024-05-15 19:14 UTC, SergeiSovras commented on homework/sergei_sovras/Homework_10/Task_10_4.py
Исправил последнее задание, добавил list comprehension

2024-05-16 10:24 UTC, eugene-okulik approved these changes

2024-05-16 10:24 UTC, merged