SSovras Task 12 was completed
eugene-okulik/SSovras pull request #12
Opened 2024-06-09 14:18 UTC by SergeiSovras

2024-06-10 10:08 UTC, eugene-okulik requested changes
Кроме того, что в коменте, всё хорошо. Обрати внимание - если тебе в момент написания кода нужно скопировать хоть что-то и вставить в другом месте кода, это явный признак, что тебе нужно воспользоваться чем-то, что позволит тебе переиспользовать код, написанный один раз.

2024-06-10 10:08 UTC, eugene-okulik commented on homework/sergei_sovras/Homework_12/Task_12.py
> +        self.area = area
Как видишь, эти 3 атрибута есть во всех подклассах. И ты копируешь один и тот же код. Именно для этого и существует наследование, чтобы то, что хочется скопировать, писать один раз и располагать это в родительском классе.

2024-06-10 11:51 UTC, SergeiSovras commented
> Кроме того, что в коменте, всё хорошо. Обрати внимание - если тебе в момент написания кода нужно скопировать хоть что-то и вставить в другом месте кода, это явный признак, что тебе нужно воспользоваться чем-то, что позволит тебе переиспользовать код, написанный один раз.
Спасибо, поправил. Вероятно, сбило с толку, что это разные классы с разными данными и хотелось их разделить, хотя у них общие атрибуты от родительского класса

2024-06-10 17:31 UTC, SergeiSovras commented on homework/sergei_sovras/Homework_12/Task_12.py
> +        self.area = area
Добавил правки, перенес общие атрибуты в родительский класс

2024-06-11 10:05 UTC, eugene-okulik approved these changes

2024-06-11 10:05 UTC, merged