SSovras Homework 17 Creating the log analyzer
eugene-okulik/SSovras pull request #17
Opened 2024-08-20 08:00 UTC by SergeiSovras

2024-08-20 09:06 UTC, eugene-okulik requested changes
Всё круто, кроме одного:
```
python Task_17.py ../../eugene_okulik/data/logs/ WARN
There is no includes the word warn
```
Но это слово там есть.  
И еще, правила именования в питоне касаются, в том числе, названий файлов. А большая буква в именованиях используется только в трех случаях: 
- классы
- True, False
- None

2024-08-21 08:05 UTC, eugene-okulik requested changes
Уже получше, но всё еще нет результата поиска:
```
python task_17.py ../../eugene_okulik/data/logs/ WARN
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:  
The file rpe-api-error.2022-02-03.3.log contains subline:
```

2024-08-21 15:08 UTC, SergeiSovras commented
> python task_17.py ../../eugene_okulik/data/logs/ WARN

Спасибо! Пока не придумал ничего лучше, чем добавить проверку левой части на коротку строку

2024-08-22 09:54 UTC, eugene-okulik approved these changes
Конечно, преобразование в нижний регистр - вещь лишняя. Но уж раз сделал, пусть будет.

2024-08-22 09:54 UTC, merged