All tasks for the Homework #4 were done
eugene-okulik/SSovras pull request #3
Opened 2024-01-15 20:07 UTC by SergeiSovras

Completed tasks were added to the file Task_4_1.py
Also, files from the previous homework were renamed to collect it more clearly

2024-01-16 18:55 UTC, eugene-okulik requested changes
Всё хорошо, но проверку на внимательность не прошел )))

2024-01-16 18:55 UTC, eugene-okulik commented on homework/sergei_sovras/Homework_4/Task_4_1.py
> +my_dict_final['dict']['i am a tuple'] = 'New element for the dict'
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты выполнил так, как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

2024-01-17 16:23 UTC, SergeiSovras commented on homework/sergei_sovras/Homework_4/Task_4_1.py
> +my_dict_final['dict']['i am a tuple'] = 'New element for the dict'
Спасибо, исправил. Добавил двойные кавычки.

2024-01-18 08:20 UTC, eugene-okulik requested changes

2024-01-18 08:20 UTC, eugene-okulik commented on homework/sergei_sovras/Homework_4/Task_4_1.py
> +my_dict_final['dict']["('i am a tuple',)"] = 'New element for the dict'
Теперь ты выполнил так, будто там написано

> добавьте элемент с ключом "('i am a tuple',)" и любым значением

Сам текст этого ключа намекает на то, как этот ключ должен выглядеть

2024-01-18 14:50 UTC, SergeiSovras commented on homework/sergei_sovras/Homework_4/Task_4_1.py
> +my_dict_final['dict']['i am a tuple'] = 'New element for the dict'
Спасибо! Точно, нужно в качестве ключа отправить кортеж.

2024-01-19 15:11 UTC, eugene-okulik approved these changes
Отлично. Я доколупался до этого кортежа чтобы обратить внимание на то, что кортеж может быть ключом словаря и на то, как выглядит кортеж с одним элементом

2024-01-19 15:11 UTC, merged